[package]
name = "browserhtml"
version.workspace = true
authors.workspace = true
license = "AGPL-3.0-or-later"
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[features]
default = ["libservo/clipboard", "js_jit", "max_log_level", "webgpu"]
gamepad = ["libservo/gamepad"]
global-hotkeys = ["dep:global-hotkey"]
crown = ["libservo/crown"]
debugmozjs = ["libservo/debugmozjs"]
jitspew = ["libservo/jitspew"]
js_backtrace = ["libservo/js_backtrace"]
js_jit = ["libservo/js_jit"]
max_log_level = ["log/release_max_level_info"]
media-gstreamer = ["libservo/media-gstreamer"]
native-bluetooth = ["libservo/native-bluetooth"]
profilemozjs = ["libservo/profilemozjs"]
refcell_backtrace = ["libservo/refcell_backtrace"]
status-tray = ["dep:tray-icon", "dep:gtk"]
tracing = ["dep:tracing", "dep:tracing-subscriber", "libservo/tracing"]
tracing-perfetto = ["tracing", "dep:tracing-perfetto"]
vello = ["libservo/vello"]
webgl_backtrace = ["libservo/webgl_backtrace"]
webgpu = ["libservo/webgpu"]
webxr = ["libservo/webxr"]

[dependencies]
axum = { version = "0.8", features = ["http2"] }
dirs = "6.0"
euclid = { workspace = true }
embedder_traits = { workspace = true }
headers = { workspace = true }
image = { workspace = true }
keyboard-types = { workspace = true }
libservo = { path = "../components/servo", features = ["background_hang_monitor", "bluetooth"], default-features = false }
log = { workspace = true }
mime_guess = { workspace = true }
parking_lot = { workspace = true }
rustls = { workspace = true, features = ["aws-lc-rs"] }
serde = { workspace = true }
serde_json = { workspace = true }
servo_config = { path = "../components/config" }
servo_config_macro = { path = "../components/config/macro" }
tokio = { workspace = true }
tower = "0.5"
tower-http = { version = "0.6", features = ["cors", "fs"] }
tracing = { workspace = true, optional = true }
tracing-perfetto = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true, features = ["env-filter"] }
tray-icon = { version = "0.21", optional = true }
url = { workspace = true }
winit = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
global-hotkey = { version = "0.7", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
gtk = { version = "0.18", optional = true }
